type: group
fields:
  streetAddress:
    type: text
    label:
      *: hksagentur.schema.field.address.streetaddress
    counter: false
  postalCode:
    type: text
    label:
      *: hksagentur.schema.field.address.postalcode
    width: 1/4
    counter: false
  addressLocality:
    label:
      *: hksagentur.schema.field.address.addressLocality
    type: text
    width: 2/4
    counter: false
  addressRegion:
    label:
      *: hksagentur.schema.field.address.addressRegion
    type: text
    width: 1/4
    counter: false
  addressCountry:
    type: text
    label:
      *: hksagentur.schema.field.address.addressCountry
    counter: false
