type: layout
label:
  *: hksagentur.schema.field.contentLayout.label
layouts:
  - "1/1"
  - "1/3, 2/3"
  - "2/3, 1/3"
selector:
  size: medium
  columns: 3
fieldsets:
  - heading
  - text
  - markdown
  - list
  - code
  - quote
  - image
  - video
settings:
  fields:
    alignment: @hksagentur/schema/fields/align-content
default:
  - type: text
    content: Text â€¦
    attrs:
      alignment: normal