type: files
label:
  *: hksagentur.schema.field.image.label
empty:
  *: hksagentur.schema.field.image.empty
query: page.images.template('image')
layout: cards
size: full
multiple: false
info: "{{ file.dimensions }} ({{ file.niceSize }})"
uploads:
  template: image