type: group
fields:
  mediaType: @hksagentur/schema/fields/media-type
  image:
    extends: @hksagentur/schema/fields/image
    layout: list
    required: true
    when:
      mediaType: image
  video:
    extends: @hksagentur/schema/fields/video
    layout: list
    required: true
    when:
      mediaType: video