type: structure
label:
  *: hksagentur.schema.field.openingHoursException.label
fields:
  date:
    type: date
    label:
      *: hksagentur.schema.field.openingHoursException.date
    required: true
    time: false
    default: today
  start:
    type: time
    label:
      *: hksagentur.schema.field.openingHoursException.start
    step:
      unit: minute
      size: 15
    required: false
    translate: false
    width: 1/2
  end:
    type: time
    label:
      *: hksagentur.schema.field.openingHoursException.end
    step:
      unit: minute
      size: 15
    required: false
    translate: false
    width: 1/2
  note:
    type: text
    icon: info
    label:
      *: hksagentur.schema.field.openingHoursException.note
columns:
  date: true
  note: true
sortable: false
sortBy: date