type: group
fields:
  extends: @hksagentur/schema/fields/name
  description:
    extends: @hksagentur/schema/fields/inline-text
    label:
      *: hksagentur.schema.field.person.description
  lineContact:
    type: line
  email: @hksagentur/schema/fields/email
  telephone: @hksagentur/schema/fields/telephone
  fax: @hksagentur/schema/fields/fax
  lineTaxonomies:
    type: line
  roles: @hksagentur/schema/fields/organization-roles