type: select
label:
  *: hksagentur.schema.field.ratio.label
placeholder:
  *: hksagentur.schema.field.ratio.placeholder
options:
  4/5: "4:5"
  1/1: "1:1"
  10/8: "10:8"
  4/3: "4:3"
  7/5: "7:5"
  3/2: "3:2"
  5/3: "5:3"
  16/9: "16:9"
  21/9: "21:9"
  3/1: "3:1"