type: files
label:
  *: hksagentur.schema.field.video.label
placeholder:
  *: hksagentur.schema.field.video.placeholder
query: page.videos.template('video')
layout: cards
size: full
multiple: false
info: "{{ file.dimensions }} ({{ file.niceSize }})"
image:
  ratio: 16/9
  cover: true
uploads:
  template: video