type: select
label:
  *: hksagentur.schema.field.videoCodec.label
options:
  - value: avc1.640029
    text: AVC (H.264)
  - value: hvc1.2.4.L123.B0
    text: HEVC (H.265)
  - value: vp9
    text: VP9
  - value: av01
    text: AV1
