type: structure
label:
  *: hksagentur.schema.field.videoFormats.label
fields:
  file:
    type: files
    label:
      *: hksagentur.schema.field.videoFormats.file
    query: model.siblings.filterBy('mime', 'in', ['video/webm', 'video/mp4'])
    required: true
    multiple: false
  codec: @hksagentur/schema/fields/video-codec