extends: @hksagentur/schema/blocks/disclosure
name:
  *: hksagentur.schema.block.accordionItem.name
tabs:
  content:
    extends: @hksagentur/schema/tabs/content
    fields:
      level:
        default: h3