name:
  *: hksagentur.schema.block.heading.name
label: "{{ text }}"
icon: title
fields:
  level: @hksagentur/schema/fields/heading-level
  text:
    extends: @hksagentur/schema/fields/heading
    label:
      *: hksagentur.schema.block.heading.text
