name:
  *: hksagentur.schema.block.image.name
icon: image
tabs:
  content:
    extends: @hksagentur/schema/tabs/content
    fields:
      location: @hksagentur/schema/fields/media-location
      image:
        extends: @hksagentur/schema/fields/image
        label:
          *: hksagentur.schema.block.image.file
        layout: list
        query: model.images
        when:
          location: kirby
      src:
        type: url
        label:
          *: hksagentur.schema.block.image.src
        when:
          location: web
      alt:
        type: text
        label:
          *: hksagentur.schema.block.image.alt
        icon: title
      caption:
        extends: @hksagentur/schema/fields/caption
        label:
          *: hksagentur.schema.block.image.caption
      link:
        label:
          *: hksagentur.schema.block.image.link
        type: text
        icon: url
  settings:
    extends: @hksagentur/schema/tabs/settings
    fields:
      ratio:
        extends: @hksagentur/schema/fields/ratio
        label:
          *: hksagentur.schema.block.image.ratio
        width: 1/2
      crop:
        type: toggle
        label:
          *: hksagentur.schema.block.image.crop
        width: 1/2
      loading:
        extends: @hksagentur/schema/fields/image-loading
        label:
          *: hksagentur.schema.block.image.loading
        width: 1/2
      priority:
        extends: @hksagentur/schema/fields/image-priority
        label:
          *: hksagentur.schema.block.image.priority
        width: 1/2