name:
  *: hksagentur.schema.block.mediaText.name
label: "{{ title }}"
icon: layout-columns
tabs:
  content:
    extends: @hksagentur/schema/tabs/content
    fields:
      level:
        extends: @hksagentur/schema/fields/heading-level
        default: h2
      title: @hksagentur/schema/fields/heading
      eyebrow: @hksagentur/schema/fields/eyebrow
      text: @hksagentur/schema/fields/rich-text
      image:
        extends: @hksagentur/schema/fields/image
        layout: list
      link:
        type: object
        fields:
          extends: @hksagentur/schema/fields/link
  settings:
    extends: @hksagentur/schema/tabs/settings
    fields:
      alignment: @hksagentur/schema/fields/align-content
      reverse: @hksagentur/schema/fields/reverse