name:
  *: hksagentur.schema.block.tabs.name
label: "{{ title }}"
icon: grid-bottom
fields:
  level:
    extends: @hksagentur/schema/fields/heading-level
    default: h2
  title: @hksagentur/schema/fields/heading
  text: @hksagentur/schema/fields/inline-text
  tabs:
    type: structure
    label:
      *: hksagentur.schema.block.tabs.tabs
    fields:
      title:
        extends: @hksagentur/schema/fields/heading
        required: true
      layout:
        extends: @hksagentur/schema/fields/content-layout
        required: true
      open:
        extends: @hksagentur/schema/fields/open
        default: false
    columns:
      title: true
      open: true
    required: true
    batch: true